package routers

import (
	"github.com/gin-gonic/gin"
	"go-schema/controllers"
)

func SetupRouter() *gin.Engine {
	r := gin.Default()

	r.Static("/fangwuzulinsystem/admin/dist", "./views/admin/dist")
	r.Static("/fangwuzulinsystem/upload", "./views/upload")
	r.Static("/fangwuzulinsystem/static", "./views")
	r.Static("/fangwuzulinsystem/option/fangwuhuxing/fangwuhuxing", "/fangwuzulinsystem/fangwuhuxing/page")

	jiaoyangGroup := r.Group("/fangwuzulinsystem")
	jiaoyangGroup.Any("/baidu/askai", func(c *gin.Context) {
		c.Request.URL.Path = "/fangwuzulinsystem/common/baidu/askai"
		r.HandleContext(c)
	})
	jiaoyangGroup.Any("/option/fangwuhuxing/fangwuhuxing", func(c *gin.Context) {
		c.Request.URL.Path = "/fangwuzulinsystem/fangwuhuxing/lists"
		r.HandleContext(c)
	})
	r.GET("/fangwuzulinsystem/ws", controllers.WebSocketControllerWebSocket)

	usersGroup := jiaoyangGroup.Group("/users")
	{
		usersGroup.POST("/register", controllers.UsersControllerRegister)
		usersGroup.POST("/login", controllers.UsersControllerLogin)
		usersGroup.GET("/logout", controllers.UsersControllerLogout)
		usersGroup.GET("/session", controllers.UsersControllerSession)
		usersGroup.GET("/page", controllers.UsersControllerPage)
		usersGroup.POST("/save", controllers.UsersControllerSave)
		usersGroup.POST("/update", controllers.UsersControllerUpdate)
		usersGroup.POST("/delete", controllers.UsersControllerDelete)
		usersGroup.GET("/info/:id", controllers.UsersControllerInfo)
	}

	fileGroup := jiaoyangGroup.Group("/file")
	{
		fileGroup.POST("/upload", controllers.FileUpload)
		fileGroup.GET("/download", controllers.FileDownload)

	}

	configGroup := jiaoyangGroup.Group("/config")
	{
		configGroup.GET("/page", controllers.ConfigControllerPage)
		configGroup.GET("/list", controllers.ConfigControllerList)
		configGroup.POST("/update", controllers.ConfigControllerUpdate)
		configGroup.GET("/info/:id", controllers.ConfigControllerInfoid)
		configGroup.GET("/info", controllers.ConfigControllerInfo)
		configGroup.GET("/detail", controllers.ConfigControllerDetail)
	}

	commonGroup := jiaoyangGroup.Group("/common")
	{
		commonGroup.GET("/option/:tableName/:columnName", controllers.CommonControllerOption)
		commonGroup.GET("/follow/:tableName/:columnName", controllers.CommonControllerFollow)
		commonGroup.POST("/sh/:tableName", controllers.CommonControllerSh)
		commonGroup.GET("/remind/:tableName/:columnName/:type", controllers.CommonControllerRemind)
		commonGroup.GET("/cal/:tableName/:columnName", controllers.CommonControllerCal)
		commonGroup.GET("/group/:tableName/:columnName", controllers.CommonControllerGroup)
		commonGroup.GET("/value/:tableName/:xColumnName/:yColumnName", controllers.CommonControllerValue)
		commonGroup.GET("/value/:tableName/:xColumnName/:yColumnName/:timeStatType", controllers.CommonControllerValueTime)
		commonGroup.GET("/matchFace", controllers.CommonControllerMatchFace)
		commonGroup.GET("/spider", controllers.CommonControllerSpider)
		commonGroup.GET("/mysqldump", controllers.CommonControllerMysqldump)
		commonGroup.POST("/baidu/askai", controllers.CommonControllerAskAI)
	}
	gukeGroup := jiaoyangGroup.Group("/guke")
	{
		gukeGroup.POST("/register", controllers.GukeRegister)
		gukeGroup.Any("/login", controllers.GukeLogin)
		gukeGroup.GET("/logout", controllers.GukeLogout)
		gukeGroup.GET("/session", controllers.GukeSession)
		gukeGroup.GET("/resetPass", controllers.GukeResetPass)
		gukeGroup.GET("/page", controllers.GukePage)
		gukeGroup.GET("/list", controllers.GukeList)
		gukeGroup.GET("/lists", controllers.GukeLists)
		gukeGroup.POST("/save", controllers.GukeSave)
		gukeGroup.POST("/add", controllers.GukeAdd)
		gukeGroup.POST("/update", controllers.GukeUpdate)
		gukeGroup.POST("/delete", controllers.GukeDelete)
		gukeGroup.GET("/info/:id", controllers.GukeInfo)
		gukeGroup.GET("/query", controllers.GukeQuery)
		gukeGroup.GET("/detail/:id", controllers.GukeDetail)
		gukeGroup.GET("/remind/:columnName/:type", controllers.GukeRemind)
		gukeGroup.GET("/group/:columnName", controllers.GukeGroup)
		gukeGroup.GET("/value/:xColumnName/:yColumnName", controllers.GukeValue)
		gukeGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.GukeValueTime)
		gukeGroup.GET("/valueMul/:xColumnName", controllers.GukeValueMul)
		gukeGroup.GET("/count", controllers.GukeCount)
	}

	yuangongGroup := jiaoyangGroup.Group("/yuangong")
	{
		yuangongGroup.POST("/register", controllers.YuangongRegister)
		yuangongGroup.Any("/login", controllers.YuangongLogin)
		yuangongGroup.GET("/logout", controllers.YuangongLogout)
		yuangongGroup.GET("/session", controllers.YuangongSession)
		yuangongGroup.GET("/resetPass", controllers.YuangongResetPass)
		yuangongGroup.GET("/page", controllers.YuangongPage)
		yuangongGroup.GET("/list", controllers.YuangongList)
		yuangongGroup.GET("/lists", controllers.YuangongLists)
		yuangongGroup.POST("/save", controllers.YuangongSave)
		yuangongGroup.POST("/add", controllers.YuangongAdd)
		yuangongGroup.POST("/update", controllers.YuangongUpdate)
		yuangongGroup.POST("/delete", controllers.YuangongDelete)
		yuangongGroup.GET("/info/:id", controllers.YuangongInfo)
		yuangongGroup.GET("/query", controllers.YuangongQuery)
		yuangongGroup.GET("/detail/:id", controllers.YuangongDetail)
		yuangongGroup.GET("/remind/:columnName/:type", controllers.YuangongRemind)
		yuangongGroup.GET("/group/:columnName", controllers.YuangongGroup)
		yuangongGroup.GET("/value/:xColumnName/:yColumnName", controllers.YuangongValue)
		yuangongGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.YuangongValueTime)
		yuangongGroup.GET("/valueMul/:xColumnName", controllers.YuangongValueMul)
		yuangongGroup.GET("/count", controllers.YuangongCount)
	}

	fangyuanxinxiGroup := jiaoyangGroup.Group("/fangyuanxinxi")
	{
		fangyuanxinxiGroup.GET("/page", controllers.FangyuanxinxiPage)
		fangyuanxinxiGroup.GET("/list", controllers.FangyuanxinxiList)
		fangyuanxinxiGroup.GET("/lists", controllers.FangyuanxinxiLists)
		fangyuanxinxiGroup.POST("/save", controllers.FangyuanxinxiSave)
		fangyuanxinxiGroup.POST("/add", controllers.FangyuanxinxiAdd)
		fangyuanxinxiGroup.POST("/update", controllers.FangyuanxinxiUpdate)
		fangyuanxinxiGroup.POST("/delete", controllers.FangyuanxinxiDelete)
		fangyuanxinxiGroup.GET("/info/:id", controllers.FangyuanxinxiInfo)
		fangyuanxinxiGroup.GET("/query", controllers.FangyuanxinxiQuery)
		fangyuanxinxiGroup.GET("/detail/:id", controllers.FangyuanxinxiDetail)
		fangyuanxinxiGroup.GET("/remind/:columnName/:type", controllers.FangyuanxinxiRemind)
		fangyuanxinxiGroup.GET("/thumbsup/:id", controllers.FangyuanxinxiThumbsup)
		fangyuanxinxiGroup.GET("autoSort", controllers.FangyuanxinxiAutoSort)
		fangyuanxinxiGroup.GET("autoSort2", controllers.FangyuanxinxiAutoSort2)
		fangyuanxinxiGroup.GET("/group/:columnName", controllers.FangyuanxinxiGroup)
		fangyuanxinxiGroup.GET("/value/:xColumnName/:yColumnName", controllers.FangyuanxinxiValue)
		fangyuanxinxiGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.FangyuanxinxiValueTime)
		fangyuanxinxiGroup.GET("/valueMul/:xColumnName", controllers.FangyuanxinxiValueMul)
		fangyuanxinxiGroup.GET("/count", controllers.FangyuanxinxiCount)
	}

	fangwuhuxingGroup := jiaoyangGroup.Group("/fangwuhuxing")
	{
		fangwuhuxingGroup.GET("/page", controllers.FangwuhuxingPage)
		fangwuhuxingGroup.GET("/list", controllers.FangwuhuxingList)
		fangwuhuxingGroup.GET("/lists", controllers.FangwuhuxingLists)
		fangwuhuxingGroup.POST("/save", controllers.FangwuhuxingSave)
		fangwuhuxingGroup.POST("/add", controllers.FangwuhuxingAdd)
		fangwuhuxingGroup.POST("/update", controllers.FangwuhuxingUpdate)
		fangwuhuxingGroup.POST("/delete", controllers.FangwuhuxingDelete)
		fangwuhuxingGroup.GET("/info/:id", controllers.FangwuhuxingInfo)
		fangwuhuxingGroup.GET("/query", controllers.FangwuhuxingQuery)
		fangwuhuxingGroup.GET("/detail/:id", controllers.FangwuhuxingDetail)
		fangwuhuxingGroup.GET("/remind/:columnName/:type", controllers.FangwuhuxingRemind)
		fangwuhuxingGroup.GET("/group/:columnName", controllers.FangwuhuxingGroup)
		fangwuhuxingGroup.GET("/value/:xColumnName/:yColumnName", controllers.FangwuhuxingValue)
		fangwuhuxingGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.FangwuhuxingValueTime)
		fangwuhuxingGroup.GET("/valueMul/:xColumnName", controllers.FangwuhuxingValueMul)
	}

	fangwuzulinGroup := jiaoyangGroup.Group("/fangwuzulin")
	{
		fangwuzulinGroup.GET("/page", controllers.FangwuzulinControllerPage)
		fangwuzulinGroup.GET("/list", controllers.FangwuzulinControllerList)
		fangwuzulinGroup.GET("/lists", controllers.FangwuzulinControllerLists)
		fangwuzulinGroup.POST("/save", controllers.FangwuzulinControllerSave)
		fangwuzulinGroup.POST("/add", controllers.FangwuzulinControllerAdd)
		fangwuzulinGroup.POST("/update", controllers.FangwuzulinControllerUpdate)
		fangwuzulinGroup.POST("/delete", controllers.FangwuzulinControllerDelete)
		fangwuzulinGroup.GET("/info/:id", controllers.FangwuzulinControllerInfo)
		fangwuzulinGroup.GET("/query", controllers.FangwuzulinControllerQuery)
		fangwuzulinGroup.GET("/detail/:id", controllers.FangwuzulinControllerDetail)
		fangwuzulinGroup.GET("/remind/:columnName/:type", controllers.FangwuzulinControllerRemind)
		fangwuzulinGroup.GET("/group/:columnName", controllers.FangwuzulinControllerGroup)
		fangwuzulinGroup.GET("/value/:xColumnName/:yColumnName", controllers.FangwuzulinControllerValue)
		fangwuzulinGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.FangwuzulinControllerValueTime)
		fangwuzulinGroup.GET("/valueMul/:xColumnName", controllers.FangwuzulinControllerValueMul)
		fangwuzulinGroup.GET("/count", controllers.FangwuzulinControllerCount)
	}

	zulinhetongGroup := jiaoyangGroup.Group("/zulinhetong")
	{
		zulinhetongGroup.GET("/page", controllers.ZulinhetongControllerPage)
		zulinhetongGroup.GET("/list", controllers.ZulinhetongControllerList)
		zulinhetongGroup.GET("/lists", controllers.ZulinhetongControllerLists)
		zulinhetongGroup.POST("/save", controllers.ZulinhetongControllerSave)
		zulinhetongGroup.POST("/add", controllers.ZulinhetongControllerAdd)
		zulinhetongGroup.POST("/update", controllers.ZulinhetongControllerUpdate)
		zulinhetongGroup.POST("/delete", controllers.ZulinhetongControllerDelete)
		zulinhetongGroup.GET("/info/:id", controllers.ZulinhetongControllerInfo)
		zulinhetongGroup.GET("/query", controllers.ZulinhetongControllerQuery)
		zulinhetongGroup.GET("/detail/:id", controllers.ZulinhetongControllerDetail)
		zulinhetongGroup.GET("/remind/:columnName/:type", controllers.ZulinhetongControllerRemind)
		zulinhetongGroup.GET("/group/:columnName", controllers.ZulinhetongControllerGroup)
		zulinhetongGroup.GET("/value/:xColumnName/:yColumnName", controllers.ZulinhetongControllerValue)
		zulinhetongGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.ZulinhetongControllerValueTime)
		zulinhetongGroup.GET("/valueMul/:xColumnName", controllers.ZulinhetongControllerValueMul)
		zulinhetongGroup.GET("/count", controllers.ZulinhetongControllerCount)
		zulinhetongGroup.POST("/shBatch", controllers.ZulinhetongControllerShBatch)
	}

	tuizushenqingGroup := jiaoyangGroup.Group("/tuizushenqing")
	{
		tuizushenqingGroup.GET("/page", controllers.TuizushenqingControllerPage)
		tuizushenqingGroup.GET("/list", controllers.TuizushenqingControllerList)
		tuizushenqingGroup.GET("/lists", controllers.TuizushenqingControllerLists)
		tuizushenqingGroup.POST("/save", controllers.TuizushenqingControllerSave)
		tuizushenqingGroup.POST("/add", controllers.TuizushenqingControllerAdd)
		tuizushenqingGroup.POST("/update", controllers.TuizushenqingControllerUpdate)
		tuizushenqingGroup.POST("/delete", controllers.TuizushenqingControllerDelete)
		tuizushenqingGroup.GET("/info/:id", controllers.TuizushenqingControllerInfo)
		tuizushenqingGroup.GET("/query", controllers.TuizushenqingControllerQuery)
		tuizushenqingGroup.GET("/detail/:id", controllers.TuizushenqingControllerDetail)
		tuizushenqingGroup.GET("/remind/:columnName/:type", controllers.TuizushenqingControllerRemind)
		tuizushenqingGroup.GET("/group/:columnName", controllers.TuizushenqingControllerGroup)
		tuizushenqingGroup.GET("/value/:xColumnName/:yColumnName", controllers.TuizushenqingControllerValue)
		tuizushenqingGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.TuizushenqingControllerValueTime)
		tuizushenqingGroup.GET("/valueMul/:xColumnName", controllers.TuizushenqingControllerValueMul)
		tuizushenqingGroup.POST("/shBatch", controllers.TuizushenqingControllerShBatch)
	}

	zulinpingjiaGroup := jiaoyangGroup.Group("/zulinpingjia")
	{
		zulinpingjiaGroup.GET("/page", controllers.ZulinpingjiaControllerPage)
		zulinpingjiaGroup.GET("/list", controllers.ZulinpingjiaControllerList)
		zulinpingjiaGroup.GET("/lists", controllers.ZulinpingjiaControllerLists)
		zulinpingjiaGroup.POST("/save", controllers.ZulinpingjiaControllerSave)
		zulinpingjiaGroup.POST("/add", controllers.ZulinpingjiaControllerAdd)
		zulinpingjiaGroup.POST("/update", controllers.ZulinpingjiaControllerUpdate)
		zulinpingjiaGroup.POST("/delete", controllers.ZulinpingjiaControllerDelete)
		zulinpingjiaGroup.GET("/info/:id", controllers.ZulinpingjiaControllerInfo)
		zulinpingjiaGroup.GET("/query", controllers.ZulinpingjiaControllerQuery)
		zulinpingjiaGroup.GET("/detail/:id", controllers.ZulinpingjiaControllerDetail)
		zulinpingjiaGroup.GET("/remind/:columnName/:type", controllers.ZulinpingjiaControllerRemind)
		zulinpingjiaGroup.GET("/group/:columnName", controllers.ZulinpingjiaControllerGroup)
		zulinpingjiaGroup.GET("/value/:xColumnName/:yColumnName", controllers.ZulinpingjiaControllerValue)
		zulinpingjiaGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.ZulinpingjiaControllerValueTime)
		zulinpingjiaGroup.GET("/valueMul/:xColumnName", controllers.ZulinpingjiaControllerValueMul)
	}
	yuyuekanfangGroup := jiaoyangGroup.Group("/yuyuekanfang")
	{
		yuyuekanfangGroup.GET("/page", controllers.YuyuekanfangControllerPage)
		yuyuekanfangGroup.GET("/list", controllers.YuyuekanfangControllerList)
		yuyuekanfangGroup.GET("/lists", controllers.YuyuekanfangControllerLists)
		yuyuekanfangGroup.POST("/save", controllers.YuyuekanfangControllerSave)
		yuyuekanfangGroup.POST("/add", controllers.YuyuekanfangControllerAdd)
		yuyuekanfangGroup.POST("/update", controllers.YuyuekanfangControllerUpdate)
		yuyuekanfangGroup.POST("/delete", controllers.YuyuekanfangControllerDelete)
		yuyuekanfangGroup.GET("/info/:id", controllers.YuyuekanfangControllerInfo)
		yuyuekanfangGroup.GET("/query", controllers.YuyuekanfangControllerQuery)
		yuyuekanfangGroup.GET("/detail/:id", controllers.YuyuekanfangControllerDetail)
		yuyuekanfangGroup.GET("/remind/:columnName/:type", controllers.YuyuekanfangControllerRemind)
		yuyuekanfangGroup.GET("/group/:columnName", controllers.YuyuekanfangControllerGroup)
		yuyuekanfangGroup.GET("/value/:xColumnName/:yColumnName", controllers.YuyuekanfangControllerValue)
		yuyuekanfangGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.YuyuekanfangControllerValueTime)
		yuyuekanfangGroup.GET("/valueMul/:xColumnName", controllers.YuyuekanfangControllerValueMul)
		yuyuekanfangGroup.POST("/shBatch", controllers.YuyuekanfangControllerShBatch)
	}

	kaoqindakaGroup := jiaoyangGroup.Group("/kaoqindaka")
	{
		kaoqindakaGroup.GET("/page", controllers.KaoqindakaControllerPage)
		kaoqindakaGroup.GET("/list", controllers.KaoqindakaControllerList)
		kaoqindakaGroup.GET("/lists", controllers.KaoqindakaControllerLists)
		kaoqindakaGroup.POST("/save", controllers.KaoqindakaControllerSave)
		kaoqindakaGroup.POST("/add", controllers.KaoqindakaControllerAdd)
		kaoqindakaGroup.POST("/update", controllers.KaoqindakaControllerUpdate)
		kaoqindakaGroup.POST("/delete", controllers.KaoqindakaControllerDelete)
		kaoqindakaGroup.GET("/info/:id", controllers.KaoqindakaControllerInfo)
		kaoqindakaGroup.GET("/query", controllers.KaoqindakaControllerQuery)
		kaoqindakaGroup.GET("/detail/:id", controllers.KaoqindakaControllerDetail)
		kaoqindakaGroup.GET("/remind/:columnName/:type", controllers.KaoqindakaControllerRemind)
		kaoqindakaGroup.GET("/group/:columnName", controllers.KaoqindakaControllerGroup)
		kaoqindakaGroup.GET("/value/:xColumnName/:yColumnName", controllers.KaoqindakaControllerValue)
		kaoqindakaGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.KaoqindakaControllerValueTime)
		kaoqindakaGroup.GET("/valueMul/:xColumnName", controllers.KaoqindakaControllerValueMul)
	}

	zufangyixiangGroup := jiaoyangGroup.Group("/zufangyixiang")
	{
		zufangyixiangGroup.GET("/page", controllers.ZufangyixiangControllerPage)
		zufangyixiangGroup.GET("/list", controllers.ZufangyixiangControllerList)
		zufangyixiangGroup.GET("/lists", controllers.ZufangyixiangControllerLists)
		zufangyixiangGroup.POST("/save", controllers.ZufangyixiangControllerSave)
		zufangyixiangGroup.POST("/add", controllers.ZufangyixiangControllerAdd)
		zufangyixiangGroup.POST("/update", controllers.ZufangyixiangControllerUpdate)
		zufangyixiangGroup.POST("/delete", controllers.ZufangyixiangControllerDelete)
		zufangyixiangGroup.GET("/info/:id", controllers.ZufangyixiangControllerInfo)
		zufangyixiangGroup.GET("/query", controllers.ZufangyixiangControllerQuery)
		zufangyixiangGroup.GET("/detail/:id", controllers.ZufangyixiangControllerDetail)
		zufangyixiangGroup.GET("/remind/:columnName/:type", controllers.ZufangyixiangControllerRemind)
		zufangyixiangGroup.GET("/group/:columnName", controllers.ZufangyixiangControllerGroup)
		zufangyixiangGroup.GET("/value/:xColumnName/:yColumnName", controllers.ZufangyixiangControllerValue)
		zufangyixiangGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.ZufangyixiangControllerValueTime)
		zufangyixiangGroup.GET("/valueMul/:xColumnName", controllers.ZufangyixiangControllerValueMul)
	}
	chatGroup := jiaoyangGroup.Group("/chat")
	{
		chatGroup.GET("/page", controllers.ChatControllerPage)
		chatGroup.GET("/list", controllers.ChatControllerList)
		chatGroup.GET("/lists", controllers.ChatControllerLists)
		chatGroup.POST("/save", controllers.ChatControllerSave)
		chatGroup.POST("/add", controllers.ChatControllerAdd)
		chatGroup.POST("/update", controllers.ChatControllerUpdate)
		chatGroup.POST("/delete", controllers.ChatControllerDelete)
		chatGroup.GET("/info/:id", controllers.ChatControllerInfo)
		chatGroup.GET("/query", controllers.ChatControllerQuery)
		chatGroup.GET("/detail/:id", controllers.ChatControllerDetail)
		chatGroup.GET("/remind/:columnName/:type", controllers.ChatControllerRemind)
		chatGroup.GET("/group/:columnName", controllers.ChatControllerGroup)
		chatGroup.GET("/value/:xColumnName/:yColumnName", controllers.ChatControllerValue)
		chatGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.ChatControllerValueTime)
		chatGroup.GET("/valueMul/:xColumnName", controllers.ChatControllerValueMul)
	}

	newstypeGroup := jiaoyangGroup.Group("/newstype")
	{
		newstypeGroup.GET("/page", controllers.NewstypeControllerPage)
		newstypeGroup.GET("/list", controllers.NewstypeControllerList)
		newstypeGroup.GET("/lists", controllers.NewstypeControllerLists)
		newstypeGroup.POST("/save", controllers.NewstypeControllerSave)
		newstypeGroup.POST("/add", controllers.NewstypeControllerAdd)
		newstypeGroup.POST("/update", controllers.NewstypeControllerUpdate)
		newstypeGroup.POST("/delete", controllers.NewstypeControllerDelete)
		newstypeGroup.GET("/info/:id", controllers.NewstypeControllerInfo)
		newstypeGroup.GET("/query", controllers.NewstypeControllerQuery)
		newstypeGroup.GET("/detail/:id", controllers.NewstypeControllerDetail)
		newstypeGroup.GET("/remind/:columnName/:type", controllers.NewstypeControllerRemind)
		newstypeGroup.GET("/group/:columnName", controllers.NewstypeControllerGroup)
		newstypeGroup.GET("/value/:xColumnName/:yColumnName", controllers.NewstypeControllerValue)
		newstypeGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.NewstypeControllerValueTime)
		newstypeGroup.GET("/valueMul/:xColumnName", controllers.NewstypeControllerValueMul)
	}

	newsGroup := jiaoyangGroup.Group("/news")
	{
		newsGroup.GET("/page", controllers.NewsControllerPage)
		newsGroup.GET("/list", controllers.NewsControllerList)
		newsGroup.GET("/lists", controllers.NewsControllerLists)
		newsGroup.POST("/save", controllers.NewsControllerSave)
		newsGroup.POST("/add", controllers.NewsControllerAdd)
		newsGroup.POST("/update", controllers.NewsControllerUpdate)
		newsGroup.POST("/delete", controllers.NewsControllerDelete)
		newsGroup.GET("/info/:id", controllers.NewsControllerInfo)
		newsGroup.GET("/query", controllers.NewsControllerQuery)
		newsGroup.GET("/detail/:id", controllers.NewsControllerDetail)
		newsGroup.GET("/remind/:columnName/:type", controllers.NewsControllerRemind)
		newsGroup.GET("/thumbsup/:id", controllers.NewsControllerThumbsup)
		newsGroup.GET("/autoSort", controllers.NewsControllerAutoSort)
		newsGroup.GET("/autoSort2", controllers.NewsControllerAutoSort2)
		newsGroup.GET("/group/:columnName", controllers.NewsControllerGroup)
		newsGroup.GET("/value/:xColumnName/:yColumnName", controllers.NewsControllerValue)
		newsGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.NewsControllerValueTime)
		newsGroup.GET("/valueMul/:xColumnName", controllers.NewsControllerValueMul)
	}

	popupRemindGroup := jiaoyangGroup.Group("/popupremind")
	{
		popupRemindGroup.GET("/page", controllers.PopupremindControllerPage)
		popupRemindGroup.GET("/list", controllers.PopupremindControllerList)
		popupRemindGroup.GET("/lists", controllers.PopupremindControllerLists)
		popupRemindGroup.POST("/save", controllers.PopupremindControllerSave)
		popupRemindGroup.POST("/add", controllers.PopupremindControllerAdd)
		popupRemindGroup.POST("/update", controllers.PopupremindControllerUpdate)
		popupRemindGroup.POST("/delete", controllers.PopupremindControllerDelete)
		popupRemindGroup.GET("/info/:id", controllers.PopupremindControllerInfo)
		popupRemindGroup.GET("/query", controllers.PopupremindControllerQuery)
		popupRemindGroup.GET("/detail/:id", controllers.PopupremindControllerDetail)
		popupRemindGroup.GET("/remind/:columnName/:type", controllers.PopupremindControllerRemind)
		popupRemindGroup.GET("/group/:columnName", controllers.PopupremindControllerGroup)
		popupRemindGroup.GET("/value/:xColumnName/:yColumnName", controllers.PopupremindControllerValue)
		popupRemindGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.PopupremindControllerValueTime)
		popupRemindGroup.GET("/valueMul/:xColumnName", controllers.PopupremindControllerValueMul)
	}

	storeupGroup := jiaoyangGroup.Group("/storeup")
	{
		storeupGroup.GET("/page", controllers.StoreupControllerPage)
		storeupGroup.GET("/list", controllers.StoreupControllerList)
		storeupGroup.GET("/lists", controllers.StoreupControllerLists)
		storeupGroup.POST("/save", controllers.StoreupControllerSave)
		storeupGroup.POST("/add", controllers.StoreupControllerAdd)
		storeupGroup.POST("/update", controllers.StoreupControllerUpdate)
		storeupGroup.POST("/delete", controllers.StoreupControllerDelete)
		storeupGroup.GET("/info/:id", controllers.StoreupControllerInfo)
		storeupGroup.GET("/query", controllers.StoreupControllerQuery)
		storeupGroup.GET("/detail/:id", controllers.StoreupControllerDetail)
		storeupGroup.GET("/remind/:columnName/:type", controllers.StoreupControllerRemind)
		storeupGroup.GET("/group/:columnName", controllers.StoreupControllerGroup)
		storeupGroup.GET("/value/:xColumnName/:yColumnName", controllers.StoreupControllerValue)
		storeupGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.StoreupControllerValueTime)
		storeupGroup.GET("/valueMul/:xColumnName", controllers.StoreupControllerValueMul)
	}

	discussfangyuanxinxiGroup := jiaoyangGroup.Group("/discussfangyuanxinxi")
	{
		discussfangyuanxinxiGroup.GET("/page", controllers.DiscussfangyuanxinxiControllerPage)
		discussfangyuanxinxiGroup.GET("/list", controllers.DiscussfangyuanxinxiControllerList)
		discussfangyuanxinxiGroup.GET("/lists", controllers.DiscussfangyuanxinxiControllerLists)
		discussfangyuanxinxiGroup.POST("/save", controllers.DiscussfangyuanxinxiControllerSave)
		discussfangyuanxinxiGroup.POST("/add", controllers.DiscussfangyuanxinxiControllerAdd)
		discussfangyuanxinxiGroup.POST("/update", controllers.DiscussfangyuanxinxiControllerUpdate)
		discussfangyuanxinxiGroup.POST("/delete", controllers.DiscussfangyuanxinxiControllerDelete)
		discussfangyuanxinxiGroup.GET("/info/:id", controllers.DiscussfangyuanxinxiControllerInfo)
		discussfangyuanxinxiGroup.GET("/query", controllers.DiscussfangyuanxinxiControllerQuery)
		discussfangyuanxinxiGroup.GET("/detail/:id", controllers.DiscussfangyuanxinxiControllerDetail)
		discussfangyuanxinxiGroup.GET("/remind/:columnName/:type", controllers.DiscussfangyuanxinxiControllerRemind)
		discussfangyuanxinxiGroup.GET("/group/:columnName", controllers.DiscussfangyuanxinxiControllerGroup)
		discussfangyuanxinxiGroup.GET("/value/:xColumnName/:yColumnName", controllers.DiscussfangyuanxinxiControllerValue)
		discussfangyuanxinxiGroup.GET("/value/:xColumnName/:yColumnName/:timeStatType", controllers.DiscussfangyuanxinxiControllerValueTime)
		discussfangyuanxinxiGroup.GET("/valueMul/:xColumnName", controllers.DiscussfangyuanxinxiControllerValueMul)
	}

	return r
}
